# Generated by Django 5.1.2 on 2024-10-14 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=30, verbose_name='Familyasi')),
                ('father_name', models.CharField(max_length=30, verbose_name='Otasini Ismi')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefon Nomeri')),
                ('family_phone_number', models.CharField(max_length=100, verbose_name='Oilasini Nomeri')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan Sanasi")),
                ('payment_date', models.DateField(verbose_name="To'lov Kuni")),
                ('brith', models.DateField(verbose_name="Tug'ilgan yili")),
                ('paid', models.BooleanField(default=False, verbose_name="To'landi Yoki To'lanmadi")),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="To'lov Narxi")),
                ('course', models.CharField(choices=[('Frontend', 'Fronted'), ('Backend', 'Backend'), ('FullStack', 'FullStack'), ('Kompyuter Savodxonligi', 'Kompyuter Savodxonligi')], max_length=100, verbose_name="O'quv Kursi")),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name="To'lov Narxi")),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name="To'lov Kuni")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
